"use client";

import Link from "next/link";
import Image from "next/image";
import {use,useState} from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {AppShell} from "@/components/AppShell";
import {api} from "@/lib/api";

type Detail={plannerTasks?:Array<Record<string,unknown>>;commits?:Array<Record<string,unknown>>;components?:string[];files?:string[];userChanges?:string[];systemChanges?:string[];technicalChanges?:string[];verificationCommands?:Array<{command:string;status:string;reportPath?:string}>;stagingResults?:Record<string,unknown>;migration?:Record<string,unknown>;risks?:string[];unverified?:string[];externalImpact?:string[];estimatedDowntime?:string;rollback?:Record<string,unknown>;plannerDecision?:string;preflight?:Record<string,unknown>;evidencePaths?:string[];screenshotPaths?:string[];environmentContract?:{configured?:boolean;reason?:string};productionVerification?:Record<string,unknown>};
type Release={id:string;releaseKey:string;purpose:string;userSummary:string;status:string;riskLevel:string;currentSha?:string;candidateSha:string;includedTaskCount:number;hasMigration:boolean;stagingStatus:string;scheduledAt?:string;preflightHash:string;actualDeployedSha?:string;uncertainOutcome:boolean;detail:Detail};
type Event={id:string;actorLabel:string;previousStatus?:string;nextStatus:string;commitSha:string;result:string;reportPath?:string;reason?:string;createdAt:string};

export default function ReleaseDetail({params}:{params:Promise<{id:string}>}){
 const {id}=use(params); const [schedule,setSchedule]=useState(""); const qc=useQueryClient();
 const release=useQuery({queryKey:["admin-release",id],queryFn:()=>api<Release>(`/admin/releases/${id}`),enabled:!!id});
 const events=useQuery({queryKey:["admin-release-events",id],queryFn:()=>api<Event[]>(`/admin/releases/${id}/events`),enabled:!!id});
 const mutate=useMutation({mutationFn:({action,body,key}:{action:string;body:unknown;key?:string})=>api<Release>(`/admin/releases/${id}/${action}`,{method:"POST",headers:key?{"Idempotency-Key":key}:{},body:JSON.stringify(body)}),onSuccess:()=>{qc.invalidateQueries({queryKey:["admin-release",id]});qc.invalidateQueries({queryKey:["admin-release-events",id]})}});
 const r=release.data,d=r?.detail??{},environmentReady=d.environmentContract?.configured===true;
 const approve=(scheduled:boolean)=>{if(!r)return; mutate.mutate({action:"approve",key:crypto.randomUUID(),body:{commitSha:r.candidateSha,environment:"PRODUCTION",scheduledAt:scheduled?new Date(`${schedule}:00+09:00`).toISOString():null}})};
 return <AppShell kicker="RELEASE CONTROL PLANE" title={r?.releaseKey??"Release 상세"}><Link href="/admin/releases" className="text-sm text-coral underline">← Releases</Link>
  {!environmentReady&&<section className="mt-5 border border-amber-200 bg-amber-50 p-5"><b>실제 배포 환경 미구성</b><p className="mt-1 text-sm">{d.environmentContract?.reason??"스테이징·revision 확인·rollback 계약이 필요합니다."}</p><p className="mt-2 text-xs">승인 자료를 검토할 수 있지만 실제 운영 실행은 연결되지 않습니다.</p></section>}
  {r&&<div className="mt-5 flex justify-end"><Link href={`/admin/releases/${r.id}/report`} className="rounded-pill bg-coral px-4 py-2 text-sm font-semibold text-white">개발 검증보고서 HTML 보기</Link></div>}
  {r&&<><section className="mt-6 grid gap-4 md:grid-cols-3"><Card title="사용자 관점 변화"><p>{r.userSummary}</p>{list(d.userChanges)}</Card><Card title="시스템 동작 변화">{list(d.systemChanges)}</Card><Card title="기술 변경·근거">{list(d.technicalChanges)}<p className="mt-3 font-mono text-xs">{short(r.currentSha)} → {short(r.candidateSha)}</p></Card></section>
  <section className="mt-6 grid gap-5 lg:grid-cols-2"><Card title="개발 검증서"><Key label="Planner 판정" value={d.plannerDecision}/><Key label="스테이징" value={r.stagingStatus}/>{(d.verificationCommands??[]).map(x=><div key={x.command} className="mt-3 border-l-2 border-hairline pl-3 text-xs"><b>{x.status}</b><code className="mt-1 block break-all">{x.command}</code>{x.reportPath&&<span className="text-mute">근거: {x.reportPath}</span>}</div>)}<h4 className="mt-5 font-semibold">근거 경로</h4>{list(d.evidencePaths)}</Card><Card title="개발 결과 스크린샷">{(d.screenshotPaths??[]).length?(d.screenshotPaths??[]).map(path=><figure key={path} className="mt-3"><Image src={path} alt="개발 검증 화면" width={1200} height={675} unoptimized className="h-auto w-full border border-hairline"/><figcaption className="mt-1 break-all text-xs text-mute">{path.startsWith("data:")?"인라인 테스트 증거":path}</figcaption></figure>):<p className="text-sm text-amber-700">스크린샷 미제출 — 승인 전 확인이 필요합니다.</p>}</Card></section>
  <section className="mt-6 grid gap-5 lg:grid-cols-2"><Card title="위험·Migration·Rollback"><Key label="위험도" value={r.riskLevel}/><Key label="DB migration" value={r.hasMigration?"있음":"없음"}/><Key label="예상 중단" value={d.estimatedDowntime}/><h4 className="mt-4 font-semibold">알려진 위험</h4>{list(d.risks)}<h4 className="mt-4 font-semibold">미검증 범위</h4>{list(d.unverified)}<pre className="mt-4 overflow-auto bg-cloud p-3 text-xs">{JSON.stringify({migration:d.migration,rollback:d.rollback},null,2)}</pre></Card><Card title="운영 적용 확인"><Key label="승인 SHA" value={r.candidateSha}/><Key label="실제 운영 SHA" value={r.actualDeployedSha??"미확인"}/><pre className="mt-4 overflow-auto bg-cloud p-3 text-xs">{JSON.stringify(d.productionVerification??{},null,2)}</pre>{r.actualDeployedSha&&r.actualDeployedSha!==r.candidateSha&&<p className="mt-3 bg-red-50 p-3 text-sm text-red-700">승인 SHA와 운영 SHA가 달라 성공으로 판정할 수 없습니다.</p>}</Card></section>
  <section className="mt-6 border border-hairline bg-white p-6"><h2 className="font-semibold">배포 결정</h2><div className="mt-4 flex flex-wrap gap-2"><button disabled={!environmentReady||r.status!=="APPROVAL_REQUIRED"||mutate.isPending} onClick={()=>approve(false)} className="rounded-pill bg-ink px-4 py-2 text-sm text-white disabled:opacity-40">지금 운영 배포 승인</button><input aria-label="예약 시각" type="datetime-local" value={schedule} onChange={e=>setSchedule(e.target.value)} className="border border-hairline px-3 py-2 text-sm"/><button disabled={!environmentReady||!schedule||r.status!=="APPROVAL_REQUIRED"} onClick={()=>approve(true)} className="rounded-pill border border-ink px-4 py-2 text-sm disabled:opacity-40">지정 시각 승인 (KST)</button>{[["hold","보류"],["cancel","승인 취소"],["discard","후보 폐기"]].map(([action,label])=><button key={action} onClick={()=>mutate.mutate({action,body:{reason:`관리자 화면에서 ${label}`}})} className="rounded-pill border border-hairline px-4 py-2 text-sm">{label}</button>)}</div>{!environmentReady&&<p className="mt-3 text-xs text-amber-700">실제 환경 계약이 없어서 즉시·예약 배포 승인 버튼이 비활성화되어 있습니다.</p>}</section>
  <section className="mt-6 border border-hairline bg-white p-6"><h2 className="font-semibold">Release 이벤트 이력</h2><ol className="mt-4 space-y-3">{(events.data??[]).map(e=><li key={e.id} className="border-l-2 border-coral pl-4 text-sm"><b>{e.previousStatus??"생성"} → {e.nextStatus}</b><p>{e.result} · {seoul(e.createdAt)}</p><p className="font-mono text-xs text-mute">{short(e.commitSha)} · {e.actorLabel}</p>{e.reason&&<p className="text-xs text-red-700">{e.reason}</p>}</li>)}</ol></section></>}
 </AppShell>;
}
function Card({title,children}:{title:string;children:React.ReactNode}){return <section className="border border-hairline bg-white p-5"><h2 className="font-semibold">{title}</h2><div className="mt-3 text-sm leading-6">{children}</div></section>} function Key({label,value}:{label:string;value?:unknown}){return <p><b>{label}:</b> {String(value??"미확인")}</p>} function list(items?:string[]){return items?.length?<ul className="mt-2 list-disc pl-5">{items.map(x=><li key={x}>{x}</li>)}</ul>:<p className="mt-2 text-mute">기록 없음</p>} function short(v?:string){return v?v.slice(0,8):"미확인"} function seoul(v:string){return new Intl.DateTimeFormat("ko-KR",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Seoul"}).format(new Date(v))+" KST"}
