CREATE TABLE content_drafts (
    id UUID PRIMARY KEY,
    owner_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    idempotency_key VARCHAR(120) NOT NULL,
    brand_name VARCHAR(120) NOT NULL,
    topic VARCHAR(200) NOT NULL,
    audience VARCHAR(300) NOT NULL,
    channel VARCHAR(30) NOT NULL,
    source_notes TEXT NOT NULL,
    evidence_notes TEXT NOT NULL,
    photo_reference_url VARCHAR(1000),
    photo_notes TEXT NOT NULL,
    style_notes TEXT NOT NULL,
    title VARCHAR(200) NOT NULL,
    body_markdown TEXT NOT NULL,
    seo_title VARCHAR(200) NOT NULL,
    meta_description VARCHAR(500) NOT NULL,
    target_keywords JSONB NOT NULL,
    evidence_used JSONB NOT NULL,
    warnings JSONB NOT NULL,
    generation_source VARCHAR(40) NOT NULL,
    provider VARCHAR(30) NOT NULL,
    model VARCHAR(80) NOT NULL,
    input_tokens BIGINT NOT NULL DEFAULT 0,
    output_tokens BIGINT NOT NULL DEFAULT 0,
    quality_score INTEGER NOT NULL DEFAULT 0,
    quality_checks JSONB NOT NULL,
    status VARCHAR(30) NOT NULL,
    approved_by UUID REFERENCES users(id) ON DELETE SET NULL,
    approved_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_content_draft_owner_idempotency UNIQUE(owner_id, idempotency_key),
    CONSTRAINT ck_content_draft_channel CHECK (channel IN ('WORDPRESS', 'NAVER', 'OTHER')),
    CONSTRAINT ck_content_draft_source CHECK (generation_source IN ('AGENTOWN_AI', 'USER_AI', 'SAFE_TEMPLATE')),
    CONSTRAINT ck_content_draft_status CHECK (status IN ('DRAFT', 'APPROVED')),
    CONSTRAINT ck_content_draft_score CHECK (quality_score BETWEEN 0 AND 100),
    CONSTRAINT ck_content_draft_tokens CHECK (input_tokens >= 0 AND output_tokens >= 0)
);

CREATE INDEX idx_content_drafts_owner_updated ON content_drafts(owner_id, updated_at DESC);
CREATE INDEX idx_content_drafts_owner_status ON content_drafts(owner_id, status, updated_at DESC);
