import {expect,test} from "@playwright/test";

test("admin release control renders evidence and records a mock scheduled approval",async({page})=>{
 const id="11111111-1111-1111-1111-111111111111",sha="a".repeat(40); let status="APPROVAL_REQUIRED"; const events:any[]=[];
 const release={id,releaseKey:"release-control-plane",purpose:"배포 승인 통제 추가",createdAt:"2026-08-27T08:00:00Z",userSummary:"관리자가 검증 자료를 확인하고 승인한 변경만 배포됩니다.",status,riskLevel:"MEDIUM",currentSha:"d".repeat(40),candidateSha:sha,includedTaskCount:1,hasMigration:true,stagingStatus:"FAKE_PASSED",preflightHash:"b".repeat(64),uncertainOutcome:false,detail:{environmentContract:{configured:true},userChanges:["Releases 화면에서 배포 시점을 선택합니다."],systemChanges:["승인 SHA와 revision을 비교합니다."],technicalChanges:["Release 계약과 상태 머신"],plannerDecision:"APPROVED",verificationCommands:[{command:"./gradlew :backend:test",status:"PASSED",reportPath:"runs/mock/verification-report.json"}],evidencePaths:["runs/mock/planner-review.json"],screenshotPaths:["data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='640' height='200'%3E%3Crect width='100%25' height='100%25' fill='%23eee'/%3E%3Ctext x='20' y='100'%3ERelease evidence%3C/text%3E%3C/svg%3E"],risks:["실제 환경은 별도 연결"],unverified:["실제 운영 배포"],estimatedDowntime:"예상 1분",migration:{classification:"ADDITIVE"},rollback:{application:"previous SHA",database:"forward-only"}}};
 await page.route("**/api/**",async route=>{const req=route.request(),path=new URL(req.url()).pathname,json=(x:unknown)=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify(x)});if(path==="/api/auth/me")return json({role:"ADMIN",email:"admin@reviewdr.kr",displayName:"운영자"});if(path==="/api/mini-homes/me")return json({title:"운영자의 회사"});if(path==="/api/admin/releases")return json([{...release,status}]);if(path===`/api/admin/releases/${id}`)return json({...release,status,scheduledAt:status==="SCHEDULED"?"2026-08-27T15:00:00Z":null});if(path===`/api/admin/releases/${id}/events`)return json(events);if(path.endsWith("/approve")){status="SCHEDULED";events.push({id:"event-1",actorLabel:"ADMIN_UI",previousStatus:"APPROVAL_REQUIRED",nextStatus:"SCHEDULED",commitSha:sha,result:"APPROVED",createdAt:"2026-08-27T14:00:00Z"});return json({...release,status,scheduledAt:"2026-08-27T15:00:00Z"})}if(path==="/api/auth/csrf")return json({});return route.fulfill({status:404,body:"{}"})});
 await page.goto("/admin/releases");await expect(page.getByText("실제 배포 환경 구성 완료")).toBeVisible();await expect(page.getByText("실제 배포 환경 미구성")).toHaveCount(0);await expect(page.getByText(/2026년 8월 27일/)).toBeVisible();await expect(page.getByRole("button",{name:"승인"})).toBeEnabled();await page.getByRole("link",{name:"상세보기"}).click();await expect(page.getByText("개발 검증서")).toBeVisible();await expect(page.getByAltText("개발 검증 화면")).toBeVisible();await expect(page.getByText("APPROVED")).toBeVisible();await page.getByRole("link",{name:"개발 검증보고서 HTML 보기"}).click();await expect(page.getByText("AGENTOWN DEVELOPMENT VERIFICATION")).toBeVisible();await page.getByRole("link",{name:"Release 상세"}).click();await page.getByLabel("예약 시각").fill("2026-08-28T00:00");await page.getByRole("button",{name:/지정 시각 승인/}).click();await expect(page.getByText("APPROVAL_REQUIRED → SCHEDULED")).toBeVisible();
 await page.screenshot({path:"public/release-evidence/release-control-plane.png",fullPage:true});
});

test("non-owner admin cannot use Releases UI",async({page})=>{await page.route("**/api/**",route=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({role:"ADMIN",email:"other@reviewdr.kr",displayName:"다른 관리자"})}));await page.goto("/admin/releases");await expect(page.getByText("admin@reviewdr.kr 운영자 계정만 접근할 수 있습니다.")).toBeVisible()});
